language: node_js
node_js: '6.9.4'
sudo: false
os: linux
dist: trusty

branches:
  only:
  - master

addons:
  apt:
    packages:
    - clang-3.3
    - build-essential

env:
  global:
    - npm_config_clang=1
    - CC=clang
    - CXX=clang++
    - MOCHA_TIMEOUT=60000
    - UNTIL_TIMEOUT=30000
    - TRAVIS_BUILD_JOB=runtests
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

notifications:
  email:
    on_success: never
    on_failure: never

install:
- npm install -g npm

script:
- ./scripts/cibuild
